### ISSUE TITLE
useGravity in CraftType configs is broken

### ISSUE THREAD

**Issue by SteveTheEngineer** [Pulverizer/Movecraft-for-Sponge#10]
Please, make useGravity and hoverLimit work

**Comment by Pulverizer** [comment]
Hi there! I had no idea anyone was testing the plugin.

If you could give more details about the situations where they do not work that would be great.
I believe they were also broken in the original BukkitAPI plugin.

**Comment by Pulverizer** [comment]
I've split this into two issues so they can be resolved separately.

**Comment by SteveTheEngineer** [comment]
> Hi there! I had no idea anyone was testing the plugin.
> 
> If you could give more details about the situations where they do not work that would be great.
> I believe they were also broken in the original BukkitAPI plugin.

It is not implemented in cccm5's movecraft but it was implemented in msummers123's movecraft (developer of movecraft before cccm5)

**Comment by SteveTheEngineer** [comment]
useGravity moves craft 1 block down on each move if there is space under craft

**Comment by STEngineer** [comment]
useGravity and hoverLimit are needed to create land vehicles

**Comment by Pulverizer** [comment]
Should be fixed in next release.
