### ISSUE TITLE
hoverLimit in CraftType configs is broken

### ISSUE THREAD

**Issue by Pulverizer** [Pulverizer/Movecraft-for-Sponge#11]
Splitting #10 into 2 issues.

**Comment by SteveTheEngineer** [comment]
hoverLimit is max step limit. I hope you know, what do I mean

**Comment by Pulverizer** [comment]
I think that this might have been replaced with `maxHeightAboveGround`?

By combining `maxHeightAboveGround` with `useGravity` (still to be fixed #10 ) and `canHoverOverWater` (still to be implemented) I think the same results can be achieved.
