### ISSUE TITLE
Typo in word "excecute"

### ISSUE THREAD

**Issue by SteveTheEngineer** [Pulverizer/Movecraft-for-Sponge#13]
https://github.com/Pulverizer/Movecraft-for-Sponge/blob/b2948ac3cb088bb8309694f5da3416c54f214b1b/src/main/java/io/github/pulverizer/movecraft/async/AsyncTask.java#L35
It must be "execute", but not "excecute"

**Comment by Pulverizer** [comment]
Fixed in rewrite branch
