### ISSUE TITLE
"You are not piloting a craft" when I am piloting a craft

### ISSUE THREAD

**Issue by eirikh1996** [Pulverizer/Movecraft-for-Sponge#16]
I piloted a craft on the public test server but when I try to enter direct control mode or move with a stick, I get "You are not piloting a craft"

**Comment by Pulverizer** [comment]
You need to right click a pilot sign.

**Comment by eirikh1996** [comment]
It was piloted when I tried to move it

**Comment by Pulverizer** [comment]
There have been some changes in regards to piloting crafts.

I should have been more specific. All details regarding getting started are in this video:
https://youtu.be/Uk-woowmNnI?t=60
