### ISSUE TITLE
Craft files not generated/not working

### ISSUE THREAD

**Issue by UAVwaffle** [Pulverizer/Movecraft-for-Sponge#55]
When I start this mod it does not generate any .craft files.  I try to use ones I have for a different fork of movecraft (forget the name, but it's the one for 1.16.2) and it doesn't reconize any of the block types (example: Invalide block type - ALL_WOOD) and it won't work at all (and whenever I join the server with said .craft files I get a constant stream of errors whenever I do anything, move, interact, etc...) if you need more info and stuff I will be more than happy to post.   sorry for the lack of bug reports, but at this time I'm in a bit of a rush.  I'll try and post more info later if needed.

**Comment by UAVwaffle** [comment]
[latest.log](https://github.com/Pulverizer/Movecraft-for-Sponge/files/5272370/latest.log)
errors when first opening

**Comment by UAVwaffle** [comment]
Heres a google drive file containing my server: https://drive.google.com/file/d/1z_3z415S48aGsTJVQKTclfskzv6Y3sW1/view?usp=sharing
in it's current state it will just pour out errors.  If you remove all the craft files it will just read "no .craft files found" or something like that with little to no errors.

**Comment by Pulverizer** [comment]
This is a duplicate. Files do not currently generate. A zip of some basic configs can be found in issue #17

**Comment by UAVwaffle** [comment]
ah thanks

**Comment by UAVwaffle** [comment]
File no longer exists

![Screenshot (2)](https://user-images.githubusercontent.com/68166007/94084850-98ff8c80-fdd4-11ea-94d8-841fe4918476.png)

**Comment by Pulverizer** [comment]
Well that's not good. Let me just go have a nosy and see what's happened to it.

**Comment by Pulverizer** [comment]
Try this one https://1drv.ms/u/s!An7pkNSr0-ZV5F1oRTrK-M7hw2Ng?e=tqy7lB

**Comment by UAVwaffle** [comment]
this one works.   Thanks!
