### ISSUE TITLE
Errors on Spongeforge

### ISSUE THREAD

**Issue by Katla-Jultak** [Pulverizer/Movecraft-for-Sponge#59]
**Describe the bug**
Sometimes when running movecraft for sponge on a spongeforge server, an error occurs that prevents ships from moving and a "java.lang.IllegalAccessError: tried to access field" is thrown infinitely in the console. The craft can be activated and piloted, but not moved. There is no indication why this happens and can only be fixed by reconstructing the server from scratch. 

**To Reproduce**
1. Create a spongeforge server with movecraft for sponge. 
2. Create a basic craft. 
3. Pilot the craft.
4. Attempt to move the craft.
5. See error in console. 

**Expected behavior**
Ships should be able to move with no problem. 

**Screenshots**
![Screen Shot 2020-10-04 at 7 31 27 PM](https://user-images.githubusercontent.com/64349713/95035148-c62c2480-0689-11eb-9132-859f747b5c05.png)

**Versions (please complete the following information):**
 - Movecraft: 0.35
 - Sponge: spongeforge-1.12.2-2838-7.3.0
- Forge: forge-1.12.2-14.23.5.2854

**Additional context**
Occurred alongside other mods in an already established mc world.

**Comment by Pulverizer** [comment]
Closing this as no more reports have occurred and there is now newer versions of both sponge and movecraft.
